### ISSUE TITLE
sunrgbd_pc_bbox_votes_50k_v1_train

### ISSUE THREAD

**Issue by XT-1997** [yikaiw/TokenFusion#8]
Hi, /sunrgbd/sunrgbd_pc_bbox_votes_50k_v1_train How can I get this file

**Comment by yikaiw** [comment]
Download address: https://pan.baidu.com/s/1LDZA6d-3eQgpZpR5hONN2w
Extract code: pike

**Comment by XT-1997** [comment]
Thanks, but 'all_obbs2d_modified_nearest_has_empty.pkl' this file is not in it. I still can't run it.

**Comment by yikaiw** [comment]
The file 'all_obbs2d_modified_nearest_has_empty.pkl' is generated with the same method as 'all_obbs_modified_nearest_has_empty.pkl', but stores 2D bboxes instead of 3D bboxes.

'all_obbs_modified_nearest_has_empty.pkl' is generated in 
https://github.com/yikaiw/TokenFusion/blob/3834ccf7765bb0bd50ea729069ad5adbd6de288d/object-detection-3d/sunrgbd/sunrgbd_data.py#L342-L345
